### ISSUE TITLE
Unit tests are not run against "built" version of code?

### ISSUE THREAD

**Issue by onlywei** [jsdom/whatwg-url#43]
I recently opened a Pull Request that adds tests to check whether the URL constructor would break when a URL object (instead of string) is passed in as the second argument: https://github.com/jsdom/whatwg-url/pull/42

However, It looks like the "built" `lib/url.js` file that we get when we `npm install whatwg-url-compat` does NOT pass these tests. Tests are not run against that file, and I get an the error like this:

```
var URL = require('whatwg-url-compat').createURLConstructor();

var b = new URL("https://developer.mozilla.org");
var c = new URL("en-US/docs", b);
```

This code snippet will throw the error:
```
node_modules/whatwg-url-compat/lib/url.js:455
  return url.replace(/^[\u0000-\u001F\u0020]+|[\u0000-\u001F\u0020]+$/g, "");
             ^

TypeError: url.replace is not a function
    at trimControlChars (/Users/wei/development/urbancompass/src/js/node_modules/whatwg-url-compat/lib/url.js:455:14)
    at new URLStateMachine (/Users/wei/development/urbancompass/src/js/node_modules/whatwg-url-compat/lib/url.js:480:18)
    at URL.init (/Users/wei/development/urbancompass/src/js/node_modules/whatwg-url-compat/lib/url.js:1324:18)
    at new URL (/Users/wei/development/urbancompass/src/js/node_modules/whatwg-url-compat/lib/url.js:1344:10)
    at Object.<anonymous> (/Users/wei/development/urbancompass/src/js/url-test.js:6:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by Sebmaster** [comment]
See my [comment](https://github.com/jsdom/whatwg-url/pull/42#issuecomment-174012546).
