### ISSUE TITLE
hostname setter does not work because of wrong state override.

### ISSUE THREAD

**Issue by m4h3** [jsdom/whatwg-url#51]
using hostname setter leads to this backtrace:
 
```
TypeError: this[("parse" + this.state)] is not a function
at new URLStateMachine (/opt/node/node_modules/whatwg-url/lib/url-state-machine.js:477:43)
at Object.module.exports.basicURLParse (/opt/node/node_modules/whatwg-url/lib/url-state-machine.js:1148:15)
at URLImpl.hostname (/opt/node/node_modules/whatwg-url/lib/URL-impl.js:126:9)
at URL.set [as hostname] (/opt/node/node_modules/whatwg-url/lib/URL.js:132:25)

```

The problem lies in whatwg-url/lib/URL-impl.js +126 where stateOverride is set to "hostname" instead of "host name" as it is described in URLStateMachine prototype.

**Comment by m4h3** [comment]
the other way to see it is that the prototype is described as "host name" instead of "hostname.

**Comment by domenic** [comment]
Thanks; will publish a new version shortly. There's also some work going on to add setter tests over in https://github.com/w3c/web-platform-tests/pull/2830 which should help with this kind of thing.
